### ISSUE TITLE
nginx::config::* parameters using hiera not possible anymore?

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-nginx#1124]
I just noticed that the `nginx::config::*` parameters in my common.yaml hiera file is not being taken into account anymore. For example I have the following config in my common.yaml hiera file: 
```
nginx::config::server_tokens: 'off'
```

but still my nginx.conf file gets created with `server tokens on`. Any ideas?

I am using Puppet 4.8.2 on Debian 8 with the puppet-nginx module version 0.7.1

**Comment by wyardley** [comment]
Some discussion here, but yes, nginx::config has been a private class since this commit, so going back a couple releases now:
https://github.com/voxpupuli/puppet-nginx/commit/3104d02ed7ce75aaa360aaae58ee34e4ce6b189f

Some more discussion in:
https://github.com/voxpupuli/puppet-nginx/issues/978

basically, use `nginx::foo` vs. `nginx::config::foo`. Sorry for the inconvenience.

**Comment by hostingnuggets** [comment]
oh boy this is confusing but thanks for the reply, it works nicely like that too...
