### ISSUE TITLE
Multiple location usage

### ISSUE THREAD

**Issue by iglov** [voxpupuli/puppet-nginx#1320]
Hi there!
In my manifest i have two defined `nginx::resource::server` and one `nginx::resource::location`. Is this possible to use some one location in multiple defined servers? I've tried set `nginx::resource::location { server => ["server_resource1","server_resource2"] }`, but `server` wants string.

**Comment by SaschaDoering** [comment]
Hi,

this issue is a duplicate to https://github.com/voxpupuli/puppet-nginx/issues/1187 and solved by https://github.com/voxpupuli/puppet-nginx/commit/117b1562e9d4a3cd43083bc8fb480ec81e7891b3. So in the current version of this module it is already possible to configure one location for multiple servers -> https://github.com/voxpupuli/puppet-nginx/blob/v0.16.0/manifests/resource/location.pp#L177.
If I haven't missed anything, this issue can be closed :)

**Comment by iglov** [comment]
Hey, @SaschaDoering !
Thank you so much! ^_^
