### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by oligriffiths** [voxpupuli/puppet-nginx#161]
Hi

Is it possible to direct nginx to read the configuration file from within my project repo?

I have a config file to configure nginx for the specific vhost contained within the project, I want nginx to use this config file when booting (adds various options/rewrite rules etc to the config) when it boots?

Thanks

Oli

**Comment by 3flex** [comment]
@oligriffiths @binhnv I'm still not following, be aware that I am 100% unfamiliar with PuPHPet. It sounds like something that may be useful, but I'm trying to understand exactly what the requirements are and whether any changes are in scope for this module.

Are you saying that you want to use the `nginx::resource::vhost` type, but do something like:

```puppet
nginx::resource::vhost { 'puphpet':
  custom_file => '/path/to/custom/file'
}
```

and then have that file copied to `/etc/nginx/sites-available` just like the other vhost configs would be? Or are you trying to just link to the file from nginx somehow, and not copy the config to `sites-available`?

**Comment by 3flex** [comment]
I'm closing this for now. @oligriffiths @binhnv please comment if you have any information to add and I'll reopen. Thanks!

**Comment by oligriffiths** [comment]
Sorry for not replying. Yeah that's pretty much what im talking about. That way a general puppet config for the box can be created, but the vhost information for the specific application can be loaded from a file within a project directory for example, that way the nginx config for myapp.com can live within the myapp repo.

**Comment by 3flex** [comment]
How would you reference that custom file from PuPHPet? That won't happen automatically, you still need to copy the file somehow and PuPHPet doesn't support doing that automatically from what I can tell.

**Comment by 3flex** [comment]
Or do you want the support added here first so PuPHPet can leverage it?

**Comment by oligriffiths** [comment]
Exactly. If it's possible to specify the path to a custom vhost declaration, then PuPHPet could add support for it.

**Comment by wyardley** [comment]
It also might be nice to support custom vhost templates, and this might be another way of supporting something like what you're talking about.

Between the custom_cfg and raw appends / prepends for locations, I've found it possible to do a lot of custom things, but it should also be possible to just push the file outside of the module if that's your goal. Since conf.d and the sites-enabled directories are already included, you can also put files there from outside of the module, and they'll be included (being mindful of `$vhost_purge` / `$confd_purge` settings).
