### ISSUE TITLE
Hiera merge with multiple yaml files

### ISSUE THREAD

**Issue by jg-development** [voxpupuli/puppet-nginx#614]
Hi,
I have a problem with including multiple yaml files and hiera.
Currently only the last vhost etc. from the last yaml file will be included.
It is the actual problem from #426 

The problem is in the init.pp

```
  create_resources('nginx::resource::upstream', $nginx_upstreams)
```

With a previous hiera_hash it works, because now all hiera hashes are included.

```
  $nginx_hiera_upstreams = hiera_hash('nginx::nginx_upstreams', {})
  create_resources('nginx::resource::upstream', $nginx_hiera_upstreams)
```

It seems a good idea to hiera_hash all resources before creating them....

Greetings Jan

**Comment by wyardley** [comment]
Is this a feature that many people are interested in?

To me, hiera merge is less useful for nginx configs, but I'm sure there are use cases where it could be very helpful. I'm a bit concerned with the unintended consequences this could have for people's existing configs. Additionally, since you can't do hiera merge in the parameters section of a class, this would be a pretty big change in terms of the basic plumbing in the module (though it is something we could look at when we restructure stuff).

**Comment by ThomasLohner** [comment]
This is very useful! For example if you put all basic stuff in a `common.yaml` like default vhosts and then split environments into `production.yaml` and `staging.yaml` which contain only these vhosts. If you are concerned about compatibility with existing configs you could make this feature available with a param `hieramerge: true`. Although this doesn't make sense to me because if this behavior changes your config, it means your yaml hierachy was already broken in the first place ;-)

**Comment by igalic** [comment]
imo, this whole "feature" should be ripped out, or, at the very least, replaced with `lookup()`

**Comment by wyardley** [comment]
closing per @archii's comment in #1116

**Comment by archii** [comment]
@igalic I'm not sure which feature you're referring to above.  Do you mean `hiera_hash()`/`hiera_array()`?
