### ISSUE TITLE
changing upstream and applying configuration does reload or restart?

### ISSUE THREAD

**Issue by pallavjosh** [voxpupuli/puppet-nginx#708]
I think it should reload only but didnt find command and perameter, only $service_restart is there?

Please confirm how it is done\
Thanks

**Comment by dhoppe** [comment]
Hello, 

by default config changes will stop / start the service, but you can set `configtest_enable` to `true`. This will override the restart parameter and use `/etc/init.d/nginx reload` instead of stop / start the service. 

https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/service.pp#L63-L67
