### ISSUE TITLE
location if statement

### ISSUE THREAD

**Issue by mnothic** [voxpupuli/puppet-nginx#713]
Hello I need put into a location an if statement like this
if $x-forwarded-proto = 'https' {
   proxy_pass https://backend
}
else { 
   proxy_pass http://backend
}
some idea how I can achive this feature with this module?

**Comment by kotopes** [comment]
```
map $x-forwarded-proto $loc_proto {
    default   "@loc_204";
     "https"  "@loc_https";
     "http"    "@loc_http";
}

location / {
  try_files $uri $loc_proto;
}

location @loc_http {
   proxy_pass http://backend;
}

location @loc_https {
   proxy_pass https://backend;
}

location @loc_204 {
   return 204;
}

```

**Comment by wyardley** [comment]
@mnothic: did the proposed solution work for you? Can this be closed?

**Comment by rudybroersma** [comment]
I am having a similiar issue. I have the following code:

[code]
    location_custom_cfg => {
                             'if' => '(!-e $request_filename) { rewrite / /index.php last; } ',
                             'set' => '$appname frontend',
                             'if' => '($request_uri ~* "shop-beheer-6572") { set $appname admin; }',
                             'if' => '($request_uri ~* "admin") { set $appname admin; }',
                           },
[/code]

This codes not work, because the plugin adds a ; after the statement, which nginx does not swallow. 

I think a new option, something like 'custom_directives' would be usefull, where one can define configuration statements that are simply added without any additional parsing (eg. adding a ; at the end).

**Comment by wyardley** [comment]
@rudybroersma see
https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/location.pp#L54-L59
