### ISSUE TITLE
Add "disable_symlinks" option for nginx::config class

### ISSUE THREAD

**Issue by jurim76** [voxpupuli/puppet-nginx#847]
Please add "disable_symlinks" option in nginx::config class
By default disable_symlinks is on, that is not good for symlinked site files.

**Comment by wyardley** [comment]
It seems like the current default is 'off'
http://nginx.org/en/docs/http/ngx_http_core_module.html#disable_symlinks
Since the module doesn't explicitly set it, I think this can be worked around with a custom config append / prepend in the relevant section, though I'll leave this ticket open for more discussion.
