### ISSUE TITLE
remove $configtest_enable parameter, look into nginx::service in general

### ISSUE THREAD

**Issue by wyardley** [voxpupuli/puppet-nginx#916]
When looking into #722, it looks like 
https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/service.pp#L63-L66
and related parameters are totally broken (though strangely, I'm having a hard time actually . This code should be looked at and simplified, and the $configtest_enable param should probably be taken out (many systems already do this in their init scripts anyway).

I really don't see how the existing `nginx::service` is working at all, need to look at it more closely.

**Comment by tux-o-matic** [comment]
@wyardley part of the problem is that the module today is depending on an init/systemd script which is not managed by the module.
Since Nginx only recently added some sort of dynamic module loading, compiling Nginx isn't that unusual and there for setting the service script is left up to you.

So in service.pp, it's optional because some script might not have reload (not a standard initd function like restart) and some use cases might want to use restart rather than reload, each using a specific kill signal. But the module design today makes some the assumptions about restart.
