### ISSUE TITLE
No allowance for custom nginx source?

### ISSUE THREAD

**Issue by CameronMcAuley** [voxpupuli/puppet-nginx#962]
What is the reason for not allowing a custom source for nginx?
I need to use nginx compiled with extra modules (ModSecurity for example), but this doesn't seem to be possible with this module - for example, debian.pp can only use ‘nginx’, 'nginx-stable’,  ‘passenger’ or ‘nginx-mainline’ and $manage_repo doesn't appear to do anything if set to false.

Would it be possible to include an option to install from a custom .deb on a repo, say, on an AWS S3 bucket or something similar?

**Comment by wyardley** [comment]
@CameronMcAuley: I don't know how we'd explicitly allow a custom source easily, _but_, we do have a proposed PR to rework some of this logic in this. One proposal did include setting an option to not manage the package at all (at which point you could manage it in your site-specific code).

That said, if you disable managing the repo and configure a repo with the appropriate source, _and_ set the right nginx version in `package_ensure` instead of `present` (or `latest` if the version in the other repo is newer), you should get that package, that is, the module will install whatever package named 'nginx' comes by default from the configured repos on the system, if that makes sense.

Does that help answer your question? You're also, of course, welcome to submit a PR that implements the behavior you're describing.

**Comment by wyardley** [comment]
ps - The proposed PR would be getting rid of `manage_repo` in favor of just having `package_source` undefined, but that would become the default behavior, and the behavior would be very similar to what I outlined above.

**Comment by CameronMcAuley** [comment]
@wyardley Thanks for the reply! So, am I understanding you correctly - if manage_repo is set to false, the module will search for a package named 'nginx' in a **_local_** apt repository configured on my system, and it will install it given that I set the correct version in package_ensure?

**Comment by wyardley** [comment]
As things are now, setting `package_source` without `manage_repos` will do nothing; that's why in the future, we're likely to have this just be a single setting (`package_source`), set to `undef` to not manage repos.

As far as the authentication problem, it looks like a signing problem, but are you sure you're getting the expected nginx version from the repo you configured? You may need to handle importing the repo's GPG key (or disabling gpg checks); the module only configures the repo's gpg key when it's managing the repos.

I haven't been using Debian derived distros for a long time, but I think maybe you'll find some helpful troubleshooting info in this comment:
https://github.com/voxpupuli/puppet-nginx/issues/929#issuecomment-258691752

Specifically, you may want to take a look at the output of 
`apt-cache policy nginx`

Note also that, barring some apt plugins that pin the package source to a particular repo, you might need to specify the package version explicitly in `package_ensure` (you may need to experiment to see how it needs to be specified exactly) to make sure you're getting "your" version.

**Comment by wyardley** [comment]
You may have more luck getting help on the Puppet community slack and / or on IRC; as best I can see, the module works as currently intended, though again, we are considering re-working the default package source and some other stuff, you can follow discussion in #938 if you're interested.
