### ISSUE TITLE
Delete default site

### ISSUE THREAD

**Issue by krjensen** [voxpupuli/puppet-nginx#996]
Hi,

Is there a way to delete the default site listing on port 80?

when I run this module on Ubuntu 1604:

```
  class { 'nginx': }

  nginx::resource::vhost { 'my-website':
    www_root    => '/var/www/my-website/',
  }
```

The port 80 is still bound to the default nginx site, a quick and dirty fix is to do this

```
  class { 'nginx': }

  file { 'default-nginx-disable':
    ensure  => absent,
    path    => '/etc/nginx/sites-enabled/default',
    require => Package['nginx'],
    notify  => Service['nginx']
  }

  nginx::resource::vhost { 'my-website':
    www_root    => '/var/www/my-website/',
  }
```

**Comment by wyardley** [comment]
Short answer, you have to set `use_default_location=false`
see #904 etc.

**Comment by y2kbadbug** [comment]
Sorry to bring up an old issue, I just felt it was better than opening a new one.  I added use_default_location => false, to my server resource but it just removed the location section of that vhost.

As this issue is stating, I want to get rid of the default vhost created initially located in /etc/nginx/sites-enabled/default.

Is there another place I need to put "use_default_location" outside of the server resource?

I also feel it's worth mentioning that #904 is not related to the question asked.

Thanks!

**Comment by evanstachowiak** [comment]
@y2kbadbug you can set `nginx::server_purge: true` in hiera and that will remove all non-puppet managed files in both `sites-enabled` and `sites-available`.

**Comment by dev-e** [comment]
This directive in `/etc/nginx/nginx.conf` enables default nginx site in any way:
`  include /etc/nginx/conf.d/*.conf;`
To remove `/etc/nginx/conf.d/default.conf` use `nginx::confd_purge: true`
